const Description = () => {
    return (
        <div className="max-w-7xl mx-auto lg:text-[40px] md:text-[30px] sm:text-[30px] xs:text-[20px] xs:mt-6 lg:flex">
            <div className="lg:mr-20">
                <h1 className="font-extrabold text-[#222328]">The Community Text</h1>
                <p className=" text-[#666e75] text-[22px] max-w-[500px lg:text-[25px] xs:text-[16px]">The community text
                    Browse a collection of code snippets, resumes, and many other questions and texts that users have searched for</p>
            </div>
            <div className="xs:mt-12 sm:mt-20 md:mt-10 lg:mt-0">
                <h1 className="font-extrabold text-[#222328]">The Community Images</h1>
                <p className=" text-[#666e75] text-[22px] max-w-[500px lg:text-[25px] xs:text-[16px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
            </div>
        </div >
    )
}
export default Description